### ISSUE TITLE
Magic String

### ISSUE THREAD

**Issue by jackdh** [sadaszewski/concaveman-cpp#1]
Hey I'm trying to run this but it's missing the file:

/Users/sadaszewski/Documents/workspace/concaveman-cpp/src/main/cpp/libconcaveman.so

**Comment by sadaszewski** [comment]
Hi Jack,

You need to compile concaveman.cpp and provide the path to the resulting
.so file instead of the hard-coded /Users/sadaszewski/...etc... Hope this
helps. If not, please let me know and I will try to assist you further.

Best regards,

--
Stanislaw

**Comment by jackdh** [comment]
@sadaszewski would it be possible for you to provide a link to a precompiled version? As people looking for the python version such as myself are unlikely to have C setup ready to compile.

It would be a big help!
