### ISSUE TITLE
Imperfect results

### ISSUE THREAD

**Issue by CEXT-Dan** [sadaszewski/concaveman-cpp#18]
No matter how I adjust the parameters, I can't get this point set to solve correctly, any ideas?
![hull result](https://user-images.githubusercontent.com/26830697/139560801-a8cf576f-6f7d-4b1c-91e3-173df68597c7.jpg)

**Comment by sadaszewski** [comment]
Does it converge correctly in the JS implementation `concaveman`? This code is essentially a translation to C++.

**Comment by CEXT-Dan** [comment]
I'll try to run it with JS

**Comment by CEXT-Dan** [comment]
I got it to work with a less than 1 concavity
