### ISSUE TITLE
Visual C++ 2017 problem

### ISSUE THREAD

**Issue by manuel76413** [sadaszewski/concaveman-cpp#2]
compiled with vc2017  report  template function error!

**Comment by sadaszewski** [comment]
I noticed that VC requires the following changes:

1) Add #include <stdlib.h>
2) Comment out/remove make_unique function definition in concaveman.h
3) Add:

using std::make_unique;

instead.
4) Replace calls to random() with rand()

**Comment by manuel76413** [comment]
In dense points cases, concaveman cannot get correct results!

**Comment by sadaszewski** [comment]
It isn't a self-tuning algorithm unfortunately. You have to adjust minimum
edge length and curvature in order to allow short edges which I presume is
what you need if you have a dense point cloud.
