### ISSUE TITLE
Logic error in findCandidate?

### ISSUE THREAD

**Issue by wheeled** [sadaszewski/concaveman-cpp#8]
Thanks for making this algorithm accessible in Python.  I believe there is a logic error in the test at line 647 in concaveman.h (sorry I haven't forked it so I can't send you a pull request).  According to the comments in the mapbox js version, this test is to:
```
            // skip all points that are as close to adjacent edges (a,b) and (c,d),
            // and points that would introduce self-intersections when connected
```
The issue is that the first two tests will always return true because the distance stored in the candidate queue is less than zero.  My proposed fix is as follows:
```
//            if (std::get<0>(item) < d0 && std::get<0>(item) < d1 &&
            if (-std::get<0>(item) < d0 && -std::get<0>(item) < d1 &&
```
This dramatically improved the performance on the data I was using.  I observed the algorithm periodically "backtracked" and inserted a candidate into the hull that should have failed one of the distance tests.  This then led to other points failing the intersection tests when they didn't need to.

**Comment by wheeled** [comment]
Here is the data I was using - it represents the vertices of polygon in no particular order.  The objective was to use a concave hull to order them so that the polygon can be reconstructed.  
[West_Lindfield_boundary.csv.zip](https://github.com/sadaszewski/concaveman-cpp/files/3874137/West_Lindfield_boundary.csv.zip)

**Comment by sadaszewski** [comment]
Hi David,

Thank you very much for spotting this. Could you please make a pull
request? Thanks!

Best regards,

--
Stanislaw

**Comment by wheeled** [comment]
Done

**Comment by sadaszewski** [comment]
Thank you very much David. Great job!
